proxies:
proxy-groups:
- name: INTERNET-UMUM 🌏
  type: select
  disable-udp: false
  proxies:
  - BALANCE
  - FALLBACK
  - BESTPING
  - INTERNET-ID
  - INTERNET-SG
  use:
  - ID
  - SG
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: INTERNET-ID
  type: select
  disable-udp: false
  use:
  - ID
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: INTERNET-SG
  type: select
  disable-udp: false
  use:
  - SG
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: BALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - ID
  - SG
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: FALLBACK
  type: fallback
  disable-udp: false
  use:
  - ID
  - SG
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: BESTPING
  type: url-test
  disable-udp: false
  use:
  - ID
  - SG
  url: http://www.gstatic.com/generate_204
  interval: '300'
proxy-providers:
  ID:
    type: http
    url: "https://raw.githubusercontent.com/Andfreeee/CFM/refs/heads/main/ID.yaml"
    path: "./proxy_provider/AKUN-ID.yaml"
    interval: 300
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  SG:
    type: http
    url: "https://raw.githubusercontent.com/Andfreeee/CFM/refs/heads/main/SG.yaml"
    path: "./proxy_provider/AKUN-SG.yaml"
    interval: 300
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rules:
  - MATCH,GLOBAL
